export interface Event {
    id: string;
    title: string;
    daysLeft: string;
    startTime: string;
    latitude: number;
    longitude: number;
    live: boolean;
    distance: number;
}

export const mockEvents: Event[] = [
    {
        id: "evt-001",
        title: "Tech Innovators Meetup",
        daysLeft: "2 days",
        startTime: "10:00 AM",
        latitude: 28.6139,
        longitude: 77.2090,
        live: true,
        distance: 1.2,
    },
    {
        id: "evt-002",
        title: "Startup Pitch Night",
        daysLeft: "5 days",
        startTime: "6:30 PM",
        latitude: 28.7041,
        longitude: 77.1025,
        live: false,
        distance: 3.5,
    },
    {
        id: "evt-003",
        title: "Open Source Contribution Jam",
        daysLeft: "1 day",
        startTime: "11:00 AM",
        latitude: 12.9716,
        longitude: 77.5946,
        live: true,
        distance: 0.8,
    },
    {
        id: "evt-004",
        title: "AI & ML Conference",
        daysLeft: "12 days",
        startTime: "9:00 AM",
        latitude: 19.0760,
        longitude: 72.8777,
        live: false,
        distance: 6.4,
    },
    {
        id: "evt-005",
        title: "Product Design Workshop",
        daysLeft: "7 days",
        startTime: "2:00 PM",
        latitude: 13.0827,
        longitude: 80.2707,
        live: false,
        distance: 4.1,
    },
    {
        id: "evt-006",
        title: "Cloud Computing Bootcamp",
        daysLeft: "3 days",
        startTime: "10:30 AM",
        latitude: 22.5726,
        longitude: 88.3639,
        live: true,
        distance: 2.0,
    },
    {
        id: "evt-007",
        title: "Blockchain Builders Meetup",
        daysLeft: "9 days",
        startTime: "5:00 PM",
        latitude: 17.3850,
        longitude: 78.4867,
        live: false,
        distance: 5.7,
    },
    {
        id: "evt-008",
        title: "Frontend Dev Hangout",
        daysLeft: "Today",
        startTime: "4:00 PM",
        latitude: 28.4595,
        longitude: 77.0266,
        live: true,
        distance: 0.6,
    },
    {
        id: "evt-009",
        title: "Backend Engineering Talk",
        daysLeft: "4 days",
        startTime: "3:00 PM",
        latitude: 26.9124,
        longitude: 75.7873,
        live: false,
        distance: 7.3,
    },
    {
        id: "evt-010",
        title: "DevOps Live Workshop",
        daysLeft: "6 days",
        startTime: "1:00 PM",
        latitude: 23.0225,
        longitude: 72.5714,
        live: false,
        distance: 3.9,
    },
    {
        id: "evt-011",
        title: "Cybersecurity Awareness Session",
        daysLeft: "8 days",
        startTime: "11:30 AM",
        latitude: 21.1702,
        longitude: 72.8311,
        live: false,
        distance: 4.8,
    },
    {
        id: "evt-012",
        title: "Mobile App Hackathon",
        daysLeft: "14 days",
        startTime: "9:00 AM",
        latitude: 18.5204,
        longitude: 73.8567,
        live: false,
        distance: 6.9,
    },
    {
        id: "evt-013",
        title: "Data Science Roundtable",
        daysLeft: "2 days",
        startTime: "6:00 PM",
        latitude: 30.7333,
        longitude: 76.7794,
        live: true,
        distance: 1.4,
    },
    {
        id: "evt-014",
        title: "UI/UX Portfolio Review",
        daysLeft: "10 days",
        startTime: "12:00 PM",
        latitude: 15.2993,
        longitude: 74.1240,
        live: false,
        distance: 8.1,
    },
    {
        id: "evt-015",
        title: "Game Development Meetup",
        daysLeft: "5 days",
        startTime: "7:00 PM",
        latitude: 11.0168,
        longitude: 76.9558,
        live: false,
        distance: 3.2,
    },
    {
        id: "evt-016",
        title: "Serverless Architecture Talk",
        daysLeft: "11 days",
        startTime: "4:30 PM",
        latitude: 24.5854,
        longitude: 73.7125,
        live: false,
        distance: 9.0,
    },
    {
        id: "evt-017",
        title: "Women in Tech Panel",
        daysLeft: "3 days",
        startTime: "5:30 PM",
        latitude: 22.7196,
        longitude: 75.8577,
        live: true,
        distance: 2.6,
    },
    {
        id: "evt-018",
        title: "Open Mic for Developers",
        daysLeft: "Today",
        startTime: "8:00 PM",
        latitude: 27.1767,
        longitude: 78.0081,
        live: true,
        distance: 0.9,
    },
    {
        id: "evt-019",
        title: "System Design Masterclass",
        daysLeft: "15 days",
        startTime: "10:00 AM",
        latitude: 25.3176,
        longitude: 82.9739,
        live: false,
        distance: 12.4,
    },
    {
        id: "evt-020",
        title: "Remote Work Best Practices",
        daysLeft: "6 days",
        startTime: "1:30 PM",
        latitude: 31.1048,
        longitude: 77.1734,
        live: false,
        distance: 5.1,
    },
    {
        id: "evt-021",
        title: "AR/VR Demo Day",
        daysLeft: "9 days",
        startTime: "3:30 PM",
        latitude: 32.7266,
        longitude: 74.8570,
        live: false,
        distance: 10.7,
    },
    {
        id: "evt-022",
        title: "Tech Career Guidance Session",
        daysLeft: "1 day",
        startTime: "4:00 PM",
        latitude: 34.0837,
        longitude: 74.7973,
        live: true,
        distance: 1.8,
    },
    {
        id: "evt-023",
        title: "Competitive Programming Contest",
        daysLeft: "13 days",
        startTime: "9:30 AM",
        latitude: 26.8467,
        longitude: 80.9462,
        live: false,
        distance: 7.6,
    },
    {
        id: "evt-024",
        title: "Web Performance Optimization Talk",
        daysLeft: "4 days",
        startTime: "2:30 PM",
        latitude: 29.9457,
        longitude: 78.1642,
        live: false,
        distance: 4.4,
    },
    {
        id: "evt-025",
        title: "Community Networking Evening",
        daysLeft: "7 days",
        startTime: "6:00 PM",
        latitude: 28.5355,
        longitude: 77.3910,
        live: false,
        distance: 3.0,
    },
];
